server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location /tiles/ {
        gzip on;
        gzip_types application/octet-stream application/x-protobuf;

        add_header Access-Control-Allow-Origin   * always;
        add_header Access-Control-Allow-Methods  "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers  "Range" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
        add_header Cache-Control                 "public, max-age=86400" always;

        location ~* \.pmtiles$ {
            add_header Content-Type application/octet-stream always;
            add_header Access-Control-Allow-Origin   * always;
            add_header Access-Control-Allow-Methods  "GET, HEAD, OPTIONS" always;
            add_header Access-Control-Allow-Headers  "Range" always;
            add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
            add_header Cache-Control                 "public, max-age=86400" always;
        }
    }

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
