default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    url: <%= ENV.fetch("DATABASE_URL", "sqlite3:/data/app.sqlite3") %>
    max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *default
    database: /data/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: /data/queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: /data/cable.sqlite3
    migrations_paths: db/cable_migrate
